import * as mongoose from 'mongoose';

//JavaScript object
export const ReposSchema = new mongoose.Schema({
  id: { type: Number, required: true },
  node_id: { type: String, required: true },
  name: { type: String, required: true },
  full_name: { type: String, required: true },
  private: { type: Boolean, required: true },
  owner: {
    login: { type: String, required: true },
    id: { type: Number, required: true },
    node_id: { type: String, required: true },
    avatar_url: { type: String, required: true },
    gravatar_id: { type: String, required: true },
    url: { type: String, required: true },
    html_url: { type: String, required: true },
    followers_url: { type: String, required: true },
    following_url: { type: String, required: true },
    gists_url: { type: String, required: true },
    starred_url: { type: String, required: true },
    subscriptions_url: { type: String, required: true },
    organizations_url: { type: String, required: true },
    repos_url: { type: String, required: true },
    events_url: { type: String, required: true },
    received_events_url: { type: String, required: true },
    type: { type: String, required: true },
    site_admin: { type: Boolean, required: true },
  },
  html_url: { type: String, required: true },
  description: { type: String, required: false },
  fork: { type: Boolean, required: true },
  url: { type: String, required: true },
  forks_url: { type: String, required: true },
  keys_url: { type: String, required: true },
  collaborators_url: { type: String, required: true },
  teams_url: { type: String, required: true },
  books_url: { type: String, required: true },
  issue_events_url: { type: String, required: true },
  events_url: { type: String, required: true },
  assignees_url: { type: String, required: true },
  branches_url: { type: String, required: true },
});
